apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pyp2foa9o-nodejs
  janus-idp.io/tekton: pyp2foa9o-nodejs
  backstage.io/kubernetes-id: pyp2foa9o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pyp2foa9o-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
